### ISSUE TITLE
Hotkey for custom query does not work

### ISSUE THREAD

**Issue by eddiebergman** [nvim-treesitter/nvim-treesitter-textobjects#154] opened 2021-12-21 15:52 UTC
**Describe the bug**
Hotkey for query does not capture block.

I have [this query](https://github.com/eddiebergman/nvim-treesitter-pyfold/blob/master/queries/python/folds.scm#L5) set to fold docstrings for `Python` in my own little plugin so I can be certain the query captures correctly.
`(function_definition body: (block (expression_statement (string) @docstring)))`

I have also tested this with my plugin enabled/disabled.

I have tried this with capture groups `@docstring`, `@comment`, `@comment.inner`, `@comment.outer`

I have tried with multi line and single line string.

**To Reproduce**
```python
# Python file with docstring to yank
def f():
   """ Some text
   
   With more to follow
   """
   return 3 + 3
```

```lua
# My configuration
require('nvim-treesitter.configs') .setup({
   ...,
   textobjects = {
     select = {
        keymaps = {
          ...,                    
          ["c"] = {
            python = "(function_definition body: (block (expression_statement (string) @comment.outer)))"
          }
        }
      }
    }
   ...,
})
```

**Expected behavior**
Using `yid`, the documentation block should be yanked

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

nvim_treesitter: health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `tree-sitter` found  0.20.0 (parser generator, only needed for :TSInstallFromGrammar)
  - WARNING: `node` executable not found (only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 11.1.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - python         ✓ ✓ ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - query          ✓ ✓ ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

</code>
</details>

**Output of `nvim --version`**
```
NVIM v0.7.0-dev+734-g51306f98b
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by root@skantify

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

**Additional context**
Using [`nvim-treesitter-playground`](https://github.com/nvim-treesitter/playground) I can be certain this query highlights the documentation block.

![Screenshot_2021-12-21_16-49-58](https://user-images.githubusercontent.com/15933394/146959095-ca00dd0a-bf79-4112-8bc9-741dedd5f815.jpg)

**Comment by stsewd** [comment] 2021-12-21 17:35
this is a duplicate of https://github.com/nvim-treesitter/nvim-treesitter-textobjects/issues/65. There is another alternative to define your own textobjects in the last comment.

**Closed by stsewd** 2021-12-21 17:35 UTC
Labels: bug
