### ISSUE TITLE
Multiple move command

### ISSUE THREAD

**Issue by ofirgall** [nvim-treesitter/nvim-treesitter-textobjects#231] opened 2022-07-17 16:16 UTC
Make move command accept `{count}` before them, like any other move in vim.

For example when configure `]a` to `goto_next_start` of `@paramater.inner`, `3]a` will jump to the 3rd parameter instead of using the same bind 3 times.

**Comment by danielo515** [comment] 2022-09-01 17:17
Does this work for other actions? For example delete or change?

**Comment by danielo515** [comment] 2022-09-01 17:18
Duplicate of #208

**Closed** 2022-09-25 10:37 UTC
Labels: enhancement
